name = "NRS3Penrose"
defaultTargets = ["NRS3Penrose"]

[leanOptions]
autoImplicit = false

[[require]]
name = "NRS3MandelstamTammCramerRao"
git = "https://github.com/naype888-cloud/nrs3-mandelstam-tamm-cramer-rao.git"
rev = "19804f01c929baf62c0ecb076389576d77e828b2"

[[lean_lib]]
name = "NRS3Penrose"
